-- Priority C.2: trwałe centra gildii — skład, role, rekrutacja, wydarzenia i kronika.

BEGIN;

ALTER TABLE public.guilds
  ADD COLUMN IF NOT EXISTS recruitment_open BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS recruitment_headline TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now());

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.guilds'::regclass
      AND conname = 'guilds_recruitment_headline_length_check'
  ) THEN
    ALTER TABLE public.guilds
      ADD CONSTRAINT guilds_recruitment_headline_length_check
      CHECK (char_length(recruitment_headline) <= 160);
  END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS public.guild_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  guild_id BIGINT NOT NULL REFERENCES public.guilds(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'member'
    CHECK (role IN ('leader', 'officer', 'member', 'recruit')),
  title TEXT NOT NULL DEFAULT '' CHECK (char_length(title) <= 50),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'left')),
  joined_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT guild_members_one_membership UNIQUE (guild_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.guild_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  guild_id BIGINT NOT NULL REFERENCES public.guilds(id) ON DELETE CASCADE,
  creator_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  title TEXT NOT NULL CHECK (char_length(title) BETWEEN 3 AND 80),
  description TEXT NOT NULL DEFAULT '' CHECK (char_length(description) <= 600),
  event_type TEXT NOT NULL DEFAULT 'Inne'
    CHECK (event_type IN ('ZvZ', 'PvP', 'PvE', 'Avalon', 'Ekonomia', 'Spotkanie', 'Inne')),
  starts_at TIMESTAMPTZ NOT NULL,
  server TEXT NOT NULL DEFAULT 'Europa'
    CHECK (server IN ('Europa', 'Ameryka', 'Azja')),
  status TEXT NOT NULL DEFAULT 'scheduled'
    CHECK (status IN ('scheduled', 'completed', 'cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.guild_activity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id BIGINT NOT NULL REFERENCES public.guilds(id) ON DELETE CASCADE,
  actor_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL
    CHECK (event_type IN ('guild_created', 'member_joined', 'member_role_changed', 'member_left', 'application_received', 'application_accepted', 'application_rejected', 'event_created', 'event_cancelled', 'recruitment_updated')),
  title TEXT NOT NULL CHECK (char_length(title) BETWEEN 1 AND 140),
  details TEXT NOT NULL DEFAULT '' CHECK (char_length(details) <= 500),
  entity_type TEXT,
  entity_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

ALTER TABLE public.guild_applications
  ADD COLUMN IF NOT EXISTS guild_id BIGINT REFERENCES public.guilds(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS applicant_user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS reviewed_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now());

UPDATE public.guild_applications AS application
SET guild_id = guild.id
FROM public.guilds AS guild
WHERE application.guild_id IS NULL
  AND lower(application.guild_name) = lower(guild.name);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.guild_applications'::regclass
      AND conname = 'guild_applications_status_check'
  ) THEN
    ALTER TABLE public.guild_applications
      ADD CONSTRAINT guild_applications_status_check
      CHECK (status IN ('pending', 'accepted', 'rejected'));
  END IF;
END;
$$;

CREATE UNIQUE INDEX IF NOT EXISTS guild_applications_one_pending_idx
  ON public.guild_applications (guild_id, applicant_user_id)
  WHERE status = 'pending' AND guild_id IS NOT NULL AND applicant_user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS guild_applications_guild_created_idx
  ON public.guild_applications (guild_id, created_at DESC);
CREATE INDEX IF NOT EXISTS guild_members_guild_status_idx
  ON public.guild_members (guild_id, status, role);
CREATE INDEX IF NOT EXISTS guild_members_user_status_idx
  ON public.guild_members (user_id, status);
CREATE INDEX IF NOT EXISTS guild_events_guild_starts_idx
  ON public.guild_events (guild_id, starts_at DESC);
CREATE INDEX IF NOT EXISTS guild_activity_guild_created_idx
  ON public.guild_activity (guild_id, created_at DESC);

INSERT INTO public.guild_members (guild_id, user_id, role, title)
SELECT guilds.id, guilds.user_id, 'leader', 'Założyciel'
FROM public.guilds
ON CONFLICT (guild_id, user_id) DO UPDATE
SET role = 'leader', title = 'Założyciel', status = 'active', updated_at = timezone('utc', now());

INSERT INTO public.guild_activity (guild_id, actor_id, event_type, title, details, entity_type, entity_id, created_at)
SELECT guilds.id, guilds.user_id, 'guild_created', 'Gildia dołączyła do portalu', guilds.name, 'guild', guilds.id::text, guilds.created_at
FROM public.guilds
WHERE NOT EXISTS (
  SELECT 1 FROM public.guild_activity
  WHERE guild_activity.guild_id = guilds.id
    AND guild_activity.event_type = 'guild_created'
);

CREATE OR REPLACE FUNCTION public.bootstrap_guild_hub()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.guild_members (guild_id, user_id, role, title)
  VALUES (NEW.id, NEW.user_id, 'leader', 'Założyciel')
  ON CONFLICT (guild_id, user_id) DO NOTHING;

  INSERT INTO public.guild_activity (
    guild_id, actor_id, event_type, title, details, entity_type, entity_id
  ) VALUES (
    NEW.id, NEW.user_id, 'guild_created', 'Gildia dołączyła do portalu', NEW.name, 'guild', NEW.id::text
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS bootstrap_guild_hub_trigger ON public.guilds;
CREATE TRIGGER bootstrap_guild_hub_trigger
AFTER INSERT ON public.guilds
FOR EACH ROW EXECUTE FUNCTION public.bootstrap_guild_hub();

REVOKE ALL ON FUNCTION public.bootstrap_guild_hub() FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.service_review_guild_application(
  p_application_id UUID,
  p_guild_id BIGINT,
  p_reviewer_id UUID,
  p_decision TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  application_row public.guild_applications%ROWTYPE;
  reviewer_role TEXT;
  reviewed_timestamp TIMESTAMPTZ := pg_catalog.timezone('utc', pg_catalog.now());
BEGIN
  IF p_decision NOT IN ('accepted', 'rejected') THEN
    RAISE EXCEPTION 'Nieprawidłowa decyzja rekrutacyjna.' USING ERRCODE = '22023';
  END IF;

  SELECT CASE
    WHEN guilds.user_id = p_reviewer_id THEN 'leader'
    ELSE (
      SELECT guild_members.role
      FROM public.guild_members
      WHERE guild_members.guild_id = p_guild_id
        AND guild_members.user_id = p_reviewer_id
        AND guild_members.status = 'active'
      LIMIT 1
    )
  END
  INTO reviewer_role
  FROM public.guilds
  WHERE guilds.id = p_guild_id;

  IF reviewer_role NOT IN ('leader', 'officer') THEN
    RAISE EXCEPTION 'Brak uprawnień do rozpatrzenia podania.' USING ERRCODE = '42501';
  END IF;

  SELECT * INTO application_row
  FROM public.guild_applications
  WHERE id = p_application_id
    AND guild_id = p_guild_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Nie znaleziono podania.' USING ERRCODE = 'P0002';
  END IF;
  IF application_row.status <> 'pending' THEN
    RAISE EXCEPTION 'Podanie zostało już rozpatrzone.' USING ERRCODE = '22023';
  END IF;

  UPDATE public.guild_applications
  SET status = p_decision,
      reviewed_by = p_reviewer_id,
      reviewed_at = reviewed_timestamp,
      updated_at = reviewed_timestamp
  WHERE id = application_row.id;

  IF p_decision = 'accepted' AND application_row.applicant_user_id IS NOT NULL THEN
    INSERT INTO public.guild_members (
      guild_id, user_id, role, title, status, updated_at
    ) VALUES (
      p_guild_id, application_row.applicant_user_id, 'recruit', 'Nowy rekrut', 'active', reviewed_timestamp
    )
    ON CONFLICT ON CONSTRAINT guild_members_one_membership DO UPDATE
    SET status = 'active', updated_at = EXCLUDED.updated_at;
  END IF;

  INSERT INTO public.guild_activity (
    guild_id, actor_id, event_type, title, entity_type, entity_id
  ) VALUES (
    p_guild_id,
    p_reviewer_id,
    CASE WHEN p_decision = 'accepted' THEN 'application_accepted' ELSE 'application_rejected' END,
    CASE
      WHEN p_decision = 'accepted' THEN 'Przyjęto ' || application_row.ingame_nick
      ELSE 'Odrzucono podanie ' || application_row.ingame_nick
    END,
    'application',
    application_row.id::TEXT
  );

  RETURN pg_catalog.jsonb_build_object(
    'id', application_row.id,
    'status', p_decision,
    'member_added', p_decision = 'accepted' AND application_row.applicant_user_id IS NOT NULL
  );
END;
$$;

REVOKE ALL ON FUNCTION public.service_review_guild_application(UUID, BIGINT, UUID, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.service_review_guild_application(UUID, BIGINT, UUID, TEXT) TO service_role;

ALTER TABLE public.guild_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guild_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guild_activity ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guild_applications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public reads active guild members" ON public.guild_members;
CREATE POLICY "Public reads active guild members"
  ON public.guild_members FOR SELECT TO anon, authenticated
  USING (
    status = 'active'
    AND EXISTS (
      SELECT 1 FROM public.guilds
      WHERE guilds.id = guild_members.guild_id
        AND guilds.status = 'visible'
    )
  );

DROP POLICY IF EXISTS "Public reads guild events" ON public.guild_events;
CREATE POLICY "Public reads guild events"
  ON public.guild_events FOR SELECT TO anon, authenticated
  USING (
    status IN ('scheduled', 'completed')
    AND EXISTS (
      SELECT 1 FROM public.guilds
      WHERE guilds.id = guild_events.guild_id
        AND guilds.status = 'visible'
    )
  );

DROP POLICY IF EXISTS "Public reads guild activity" ON public.guild_activity;
CREATE POLICY "Public reads guild activity"
  ON public.guild_activity FOR SELECT TO anon, authenticated
  USING (
    event_type NOT IN ('application_received', 'application_rejected')
    AND
    EXISTS (
      SELECT 1 FROM public.guilds
      WHERE guilds.id = guild_activity.guild_id
        AND guilds.status = 'visible'
    )
  );

DROP POLICY IF EXISTS "Zalogowani mogą wysyłać aplikacje" ON public.guild_applications;

REVOKE ALL ON TABLE public.guild_members, public.guild_events, public.guild_activity, public.guild_applications FROM anon, authenticated;
GRANT SELECT ON TABLE public.guild_members, public.guild_events, public.guild_activity TO anon, authenticated;

GRANT ALL ON TABLE public.guild_members, public.guild_events, public.guild_activity, public.guild_applications TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.guild_activity_id_seq TO service_role;

COMMIT;
