-- Priority D.5: server-side market history and persistent price alerts.

BEGIN;

CREATE TABLE public.market_price_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id TEXT NOT NULL,
  region TEXT NOT NULL,
  city TEXT NOT NULL,
  quality SMALLINT NOT NULL,
  sell_price_min BIGINT NOT NULL DEFAULT 0,
  buy_price_max BIGINT NOT NULL DEFAULT 0,
  source_sell_updated_at TIMESTAMPTZ,
  source_buy_updated_at TIMESTAMPTZ,
  sampled_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT market_price_snapshots_item_check
    CHECK (char_length(item_id) BETWEEN 3 AND 80 AND item_id ~ '^[A-Z0-9_@]+$'),
  CONSTRAINT market_price_snapshots_region_check
    CHECK (region IN ('europe', 'america', 'asia')),
  CONSTRAINT market_price_snapshots_city_check
    CHECK (city IN ('Caerleon', 'Bridgewatch', 'Fort Sterling', 'Lymhurst', 'Martlock', 'Thetford', 'Brecilien')),
  CONSTRAINT market_price_snapshots_quality_check CHECK (quality BETWEEN 1 AND 5),
  CONSTRAINT market_price_snapshots_prices_check
    CHECK (sell_price_min >= 0 AND buy_price_max >= 0 AND (sell_price_min > 0 OR buy_price_max > 0)),
  CONSTRAINT market_price_snapshots_sample_unique
    UNIQUE (item_id, region, city, quality, sampled_at)
);

CREATE INDEX market_price_snapshots_retention_idx
  ON public.market_price_snapshots USING BRIN (sampled_at);

CREATE TABLE public.price_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  item_id TEXT NOT NULL,
  item_name TEXT NOT NULL,
  region TEXT NOT NULL,
  city TEXT NOT NULL,
  quality SMALLINT NOT NULL DEFAULT 1,
  price_type TEXT NOT NULL,
  direction TEXT NOT NULL,
  target_price BIGINT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  condition_met BOOLEAN NOT NULL DEFAULT false,
  last_observed_price BIGINT,
  last_checked_at TIMESTAMPTZ,
  last_triggered_at TIMESTAMPTZ,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT price_alerts_item_check
    CHECK (char_length(item_id) BETWEEN 3 AND 80 AND item_id ~ '^[A-Z0-9_@]+$'),
  CONSTRAINT price_alerts_item_name_check CHECK (char_length(item_name) BETWEEN 1 AND 120),
  CONSTRAINT price_alerts_region_check CHECK (region IN ('europe', 'america', 'asia')),
  CONSTRAINT price_alerts_city_check
    CHECK (city IN ('Caerleon', 'Bridgewatch', 'Fort Sterling', 'Lymhurst', 'Martlock', 'Thetford', 'Brecilien')),
  CONSTRAINT price_alerts_quality_check CHECK (quality BETWEEN 1 AND 5),
  CONSTRAINT price_alerts_type_check CHECK (price_type IN ('sell', 'buy')),
  CONSTRAINT price_alerts_direction_check CHECK (direction IN ('below', 'above')),
  CONSTRAINT price_alerts_type_direction_check
    CHECK ((price_type = 'sell' AND direction = 'below') OR (price_type = 'buy' AND direction = 'above')),
  CONSTRAINT price_alerts_target_check CHECK (target_price BETWEEN 1 AND 1000000000000),
  CONSTRAINT price_alerts_observed_check CHECK (last_observed_price IS NULL OR last_observed_price >= 0),
  CONSTRAINT price_alerts_error_check CHECK (last_error IS NULL OR char_length(last_error) <= 300),
  CONSTRAINT price_alerts_user_market_unique
    UNIQUE (user_id, item_id, region, city, quality, price_type)
);

CREATE INDEX price_alerts_user_updated_idx
  ON public.price_alerts (user_id, updated_at DESC);

CREATE INDEX price_alerts_active_poll_idx
  ON public.price_alerts (last_checked_at ASC NULLS FIRST)
  WHERE active = true;

ALTER TABLE public.market_price_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.price_alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users read own price alerts"
  ON public.price_alerts FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id);

REVOKE ALL ON TABLE public.market_price_snapshots FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.price_alerts FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.price_alerts TO authenticated;
GRANT ALL ON TABLE public.market_price_snapshots, public.price_alerts TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.market_price_snapshots_id_seq TO service_role;

COMMENT ON TABLE public.market_price_snapshots IS
  'Hourly-deduplicated Albion Data Project order-book samples retained by the portal backend.';
COMMENT ON TABLE public.price_alerts IS
  'Persistent per-user market thresholds evaluated by authenticated requests and scheduled jobs.';

COMMIT;
